name: Create Archive
on: 
  push:
    tags:
    - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@master
    
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ steps.get-latest-tag.outputs.tag }}
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
