name: Release
on:
  push:
    branches:
      - main

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        uses: jef/conventional-commits-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
