name: Create Archive
on: 
  push:
    branches:
      - main
      
jobs:
  #Creates a Minor release
  release-on-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
  #Creates a Package and attaches it to new generated Tag
  build:
    needs: release-on-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag:  ${{needs.release-on-push.outputs.tag}}
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
